pipeline {
    agent any
    stages {
        stage("Set Variable") {
            steps {
                script {
                    IMAGE_NAME_FE = "wnsdud12365/peekpick-react"
                    IMAGE_STORAGE = "https://registry.hub.docker.com"
                    IMAGE_STORAGE_CREDENTIAL = "docker-hub"
                    CONTAINER_NAME_FE = "peekpick_fe"
                    PROJECT_DIR_FE = "frontend"
                }
            }
        }

        // 컨테이너 클리닝
        stage("container cleaning") {
            steps{
                sh "docker ps -q -f name=${CONTAINER_NAME_FE} | xargs --no-run-if-empty docker container stop"    
                sh "docker container ls -a -q -f name=${CONTAINER_NAME_FE} | xargs --no-run-if-empty docker rm"
            }
        }

        // 이미지 삭제
        stage("image cleaning") {
            steps{
                sh "docker images ${IMAGE_NAME_FE} -q | xargs -r docker rmi -f"
            }
        }
        
        // 도커 이미지 빌드
        stage("image build") {
            steps {
                dir("${PROJECT_DIR_FE}") {
                    script {
                        sh "docker build --no-cache -t ${IMAGE_NAME_FE} ."
                    }
                }
            }
        }

        // 컨테이너 실행
        stage("fe container run") {
            steps {
                script {
                    sh "docker run -d -p 3000:3000 --name ${CONTAINER_NAME_FE} ${IMAGE_NAME_FE}"
                }
            }
        }
    }
}