pipeline {
    agent any
    stages {
        stage("Set Variable") {
            steps {
                script {
                    IMAGE_NAME_BE = "wnsdud12365/peekpick-springboot"
                    IMAGE_STORAGE = "https://registry.hub.docker.com"
                    IMAGE_STORAGE_CREDENTIAL = "docker-hub"
                    APPLICATION_YML_PATH = "/usr/spring/resources"
                    CONTAINER_NAME_BE = "peekpick_be"
                    PROJECT_DIR_BE = "backend"
                }
            }
        }

        // 설정파일 참조
        stage("copy yml") {
            steps {
                sh "cp -r ${APPLICATION_YML_PATH} ${PROJECT_DIR_BE}/src/main"
            }
        }

        // 백엔드 프로젝트 빌드
        stage("be build") {
            // build
            steps{
                sh """
                cd ${PROJECT_DIR_BE}
                chmod 777 ./gradlew
                ls -al
                pwd
                ./gradlew clean build
                """
            }
        }

        // 컨테이너 클리닝
        stage("container cleaning") {
            steps{
                sh "docker ps -q -f name=${CONTAINER_NAME_BE} | xargs --no-run-if-empty docker container stop"    
                sh "docker container ls -a -q -f name=${CONTAINER_NAME_BE} | xargs --no-run-if-empty docker rm"
            }
        }

        // 이미지 삭제
        stage("image cleaning") {
            steps{
                sh "docker images ${IMAGE_NAME_BE} -q | xargs -r docker rmi -f"
            }
        }
        
        // 도커 이미지 빌드
        stage("be image build") {
            steps {
                dir("${PROJECT_DIR_BE}") {
                    script {
                        sh "docker build --no-cache -t ${IMAGE_NAME_BE} ."
                    }
                }
            }
        }

        // 컨테이너 실행
        stage("be container run") {
            steps {
                script {
                    sh "docker run -d -p 8081:8081 --name ${CONTAINER_NAME_BE} ${IMAGE_NAME_BE}"
                }
            }
        }
    }
}